### ISSUE TITLE
Help configuring Typescript for react-universally

### ISSUE THREAD

**Issue by Falieson** [Falieson/react-universally--typescript#1]
This repo is my fork of http://github.com/ctrlplusb/react-universally where I want to configure TS.

My attempt is in this commit: https://github.com/Falieson/react-universally--typescript/commit/ce0f76132e61231000c16b323e9df6a83b68d372

- I've been referencing this rejected PR: https://github.com/ctrlplusb/react-universally/pull/241
- I'm using my tsconfig.json / tslint.json from another project

what I've learned while trying to figure this out so far

adding this to my `server/index.js`
```
process.on('unhandledRejection', (reason, p) => {
  console.log(reason.stack);
});
```

outputs:
```
REQUEST: Received for "/"
Error: Invariant Violation: Invalid tag: http://0.0.0.0:7331/client/68f9c2efb9  5ab7eb43bf6edb10fafb26.tsx

  - invariant.js:44 invariant
    [fork-react-universally--typescript]/[fbjs]/lib/invariant.js:44:15

  - ReactDOMComponent.js:345 validateDangerousTag
    [fork-react-universally--typescript]/[react-dom]/lib/ReactDOMComponent.js:34    5:74

  - ReactDOMComponent.js:372 new ReactDOMComponent
    [fork-react-universally--typescript]/[react-dom]/lib/ReactDOMComponent.js:37    2:3

  - ReactHostComponent.js:41 Object.createInternalComponent
    [fork-react-universally--typescript]/[react-dom]/lib/ReactHostComponent.js:4    1:10

  - instantiateReactComponent.js:79 ReactCompositeComponentWrapper.instantiateRe    actComponent [as _instantiateReactComponent]
    [fork-react-universally--typescript]/[react-dom]/lib/instantiateReactCompone    nt.js:79:37

  - ReactCompositeComponent.js:366 ReactCompositeComponentWrapper.performInitial    Mount
    [fork-react-universally--typescript]/[react-dom]/lib/ReactCompositeComponent    .js:366:22

  - ReactCompositeComponent.js:257 ReactCompositeComponentWrapper.mountComponent    [fork-react-universally--typescript]/[react-dom]/lib/ReactCompositeComponent    .js:257:21

  - ReactReconciler.js:45 Object.mountComponent
    [fork-react-universally--typescript]/[react-dom]/lib/ReactReconciler.js:45:3    5

  - ReactCompositeComponent.js:370 ReactCompositeComponentWrapper.performInitial    Mount
    [fork-react-universally--typescript]/[react-dom]/lib/ReactCompositeComponent    .js:370:34

  - ReactCompositeComponent.js:257 ReactCompositeComponentWrapper.mountComponent    [fork-react-universally--typescript]/[react-dom]/lib/ReactCompositeComponent    .js:257:21
```

Additionally, when I `run build`, I get in my build/client/ directory 2 files: index-522575c9f6052d599d68.js and 68f9c2efb95ab7eb43bf6edb10fafb26.tsx . Shouldn't the output be a single .js file?

If you can fix this with a reply/comment great, if you can provide a PR even better. 

Thank you!

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=51549821)](https://www.bountysource.com/issues/51549821-help-configuring-typescript-for-react-universally)

**Comment by upvalue** [comment]
I am not familiar with HappyPack, but cribbing off this: https://github.com/TypeStrong/ts-loader/issues/336#issuecomment-305958183 it seems like the TypeScript compiler was not actually running.

There definitely should not be ts(x) files in the resulting build, and it seems like it was being treated as some kind of asset.

This runs and can catch a type error in index.tsx if I introduce one.

**Comment by Falieson** [comment]
@ioddly Thank you!! I'm accepting this

**Comment by quantuminformation** [comment]
good job
